### ISSUE TITLE
https://kiplepay.com/

### ISSUE THREAD

**Issue by LaiYingLeong** [a2000-erp-team/Nopcommerce#1]
Raja requested to use another gateway, kiple

**Comment by LaiYingLeong** [comment]
Please use the Kiplepay api to add in new Mode of payment into Nopcommerce
https://drive.google.com/drive/folders/1WoiJUOw_6rMv5A0ePSjTgsIYjGQCuF1M

**Comment by ykauniqe** [comment]
Changeset 10439
