### ISSUE TITLE
Purchase Order was activated as Payment Method but during checkout no payment option shown

### ISSUE THREAD

**Issue by LaiYingLeong** [a2000-erp-team/Nopcommerce#14]
![image](https://user-images.githubusercontent.com/47965549/58147026-461b3f80-7c8b-11e9-93db-dfa9c07dd1c6.png)
![image](https://user-images.githubusercontent.com/47965549/58147054-5fbc8700-7c8b-11e9-8e63-3a6446707ba0.png)

**Comment by ykauniqe** [comment]
@TTS will provide the changes.
