### ISSUE TITLE
Missing Plugins

### ISSUE THREAD

**Issue by jayprimeliquor** [a2000-erp-team/Nopcommerce#2]
After the adjustment from before, 2 plugins we own is missing:

- Smart products collection
- Rich Blog

**Comment by jayprimeliquor** [comment]
Thanks, the plugin is appeared. However its not really functioning.

"Smart Products Collection" is not functioning, everything is enabled:
![image](https://user-images.githubusercontent.com/48204668/53941317-c00f4400-40f2-11e9-897a-a1ef3b288daa.png)

If it works, it should look something like this:
<img width="507" alt="screencap" src="https://user-images.githubusercontent.com/48204668/53941337-c9001580-40f2-11e9-830d-34d8edb05c6a.PNG">

**Comment by LaiYingLeong** [comment]
Already go live
