### ISSUE TITLE
Changing "Promotions" Style

### ISSUE THREAD

**Issue by jayprimeliquor** [a2000-erp-team/Nopcommerce#3]
If you look at our test site now: http://a21.sg:93/cellar
You can see under the hero banner, there is a "Promotions" sections, featuring products we manually tick under "Display on HomePage"

-How do we change the title from "Promotions" to "Featured products"
-Can we change the style similar to our old website? (www.cellarbration.com.sg)
EG. A grid that has sliders, and display 2 boxes on mobile

**Comment by ykauniqe** [comment]
you should go to manage menu and you can manage as you like.
![MenageMenus](https://user-images.githubusercontent.com/47884745/54187370-c4b16f00-44db-11e9-822e-438e99bfa132.PNG)

**Comment by LaiYingLeong** [comment]
Already go live
