### ISSUE TITLE
Arrows on JCarousel Plugin is transparent

### ISSUE THREAD

**Issue by jayprimeliquor** [a2000-erp-team/Nopcommerce#4]
Upon Inspecting the element, I realised the arrows are uploaded as an image (i think), hence the color does not complement our website body back ground color, making it transparent.

Take a look at this screenshot:
![image.png](https://images.zenhubusercontent.com/5c7f6adbeab6a53fac8e23f4/6f2e01de-90b3-479e-b9b6-8b8a738ff324)

Can you make some changes in the CSS, to make the arrows visible?

**Comment by LaiYingLeong** [comment]
Already go live
